### ISSUE TITLE
how to use these?

### ISSUE THREAD

**Issue by chr1s78** [gbreen12/EsriSwiftUI#1]

**Comment by gbreen12** [comment]
Good question! I'll try to get an example written up on the readme asap.

**Comment by gbreen12** [comment]
I added a simple example that switches between two maps. Let me know if you have other questions

**Comment by chr1s78** [comment]
thank u very much! but i have another question, when i run this , there is a message on my mobile screen ,"Licensed for  Developer Use Only". I have the arcGIS key, but where should i use this in my code?

**Comment by gbreen12** [comment]
There are a few places it might make sense. The easiest is just in the init of the view model. Alternately you could do it when the app starts up in the init of the `App.swift` file
